[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
python_functions = test_*

addopts =
    -v
    -ra
    --strict-markers
    --strict-config
    --cov=pyrestkit
    --cov-report=term-missing
    --cov-report=html
    --cov-report=xml